# Generated by Django 2.2.3 on 2019-09-22 08:38

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to=users.models.User.get_file_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(default=2),
        ),
    ]
