# Generated by Django 2.2.3 on 2019-09-24 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190922_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='u_image',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nickname',
            new_name='u_nickname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='u_role',
        ),
    ]
