# Generated by Django 2.2.3 on 2019-09-28 05:14

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190924_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='u_image',
            new_name='u_image_0',
        ),
        migrations.AddField(
            model_name='user',
            name='u_image_1',
            field=models.ImageField(null=True, upload_to=users.models.User.get_file_path_1),
        ),
        migrations.AddField(
            model_name='user',
            name='u_image_2',
            field=models.ImageField(null=True, upload_to=users.models.User.get_file_path_2),
        ),
    ]
