# Generated by Django 2.2.3 on 2019-09-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20190924_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='cnt_class',
        ),
        migrations.AddField(
            model_name='course',
            name='cnt_sign',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='c_code',
            field=models.CharField(default='C123456', max_length=10),
        ),
    ]
