# Generated by Django 2.2.3 on 2019-11-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20190925_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_quit',
            field=models.BooleanField(default=False),
        ),
    ]
